### ISSUE TITLE
Fix the Edit on GitHub link

### ISSUE THREAD

**Issue by MichaelCurrin** [getmeli/meli-docs#9]
This button currently works but is not smooth.

## Steps to reproduce bug

1. Go to homepage (or any page) https://docs.meli.sh/
2. Click on _Edit on Github_ button. It's link is https://github.com/getmeli/meli-docs/tree/master/src/data/docs/index.md
3. When you click through, you'll be warned that the branch `master` does not exist and that it will use `latest` instead.

## Solution

Change the button to use `latest` instead of `master` in the URL.

Therefore a change to `.env.example` is necessary.

Outside of the codebase, if there are any environment variables set on the GH repo secrets or remote server, then the env variable needs to be updated there to be the maintainer.

**Comment by MichaelCurrin** [comment]
Additional details I found digging in the code:

- I found this component which sets the `href` as the github URL, [here](https://github.com/getmeli/meli-docs/blob/c26a50cddb558a68fa3b0fe53e8b83b0479944ac/src/components/shared/banner/banner.js#L9)
- And `Banner` URL is set in `Content` [here](https://github.com/getmeli/meli-docs/blob/e47acb84bb725a7fb4f22e880a1664069bbd9723/src/components/pages/doc-page/content/content.js#L39)
- That value gets set [here](https://github.com/getmeli/meli-docs/blob/c26a50cddb558a68fa3b0fe53e8b83b0479944ac/src/templates/doc-page.js#L25) in `docs-page.js`. 
- Which comes from the env value here: [here](https://github.com/getmeli/meli-docs/blob/a515b636bf054e58ab8f3c6115a2371329b706c6/gatsby-node.js#L46)

**Comment by gempain** [comment]
@MichaelCurrin thanks so much for digging into this. The link is controlled by the `GATSBY_GITHUB_DOCS_URL` environment variable which is incorrect in the current setup. I'll update this right away !
